---
title: "Patrones de Homicidios en México"
format:
  dashboard:
    logo: images/lytica_logo_black_nobk.png
editor_options: 
  chunk_output_type: console
---

# Heatmap Valores Absolutos

## Row 

```{r}
#| label: librerias
#| echo: false
#| message: false

library(tidyverse)
library(styleBreton)
library(sf)
```

### Column {width=80%}

::: {.card title="Mapa de Calor con Cuenta de Homicidios"}

```{r}
#| label: mapa de calor homicidios
#| fig.width: 16
#| fig.height: 6

# importa datos
dt_homic <- 
  read_rds("raw_data/homicidios.rds")

# plot mapa de calor
dt_homic  |> 
  filter(año > 2015) |> 
  na.omit() |>  
  mutate(estado = factor(estado, 
                         levels = rev(sort(unique(estado)))),
         texto = paste0(estado, "\n",
                        año, mes, "\n",
                        homicidios)) |> 
  ggplot(aes(x = fecha,
             y = estado, 
             fill = homicidios)) +
    geom_tile(color = "grey70", 
              alpha = 0.85) +
    scale_fill_gradient(low = "#FFFFFF", 
                        high = "#7B0303",
                        expand = c(0,0)) +
    geom_vline(aes(xintercept = as_date("2018-12-01"), 
                   alpha = 0.15), 
               linewidth = 3, 
               color = "darkgrey") +
    theme_breton() +
    theme(plot.background = element_blank(),
          panel.background = element_rect(fill = "#FFFFFF"),
          legend.position = "top") +
    labs(title = "Patrones de la Violencia Homicida en México",
         subtitle = "Víctimas de homicidio doloso acumuladas cada mes por Entidad Federativa, de enero de 2016 a abril de 2024.",
         x = NULL,
         y = NULL,
         caption = "Fuente: Reportes de Incidencia Delictiva; 
         Secretariado Ejecutivo del Sistema Nacional de Seguridad Pública, 
         Gobierno de México.<br>
         Visualización: Juan L. Bretón, PMP | @juanlbreton",
         fill = "Víctimas por Mes") +
    guides(alpha = guide_legend("Inicio de Sexenio", 
                                label = FALSE,
                                title.vjust =  -0.01)) +
    scale_y_discrete(expand = c(0, 0)) +
    scale_x_date(expand = c(0, 0)) #-> ab1

# plotly::ggplotly(ab1)
```


:::

### Column {width=20%}


```{r}
#| label: texto explicativo l1

htmltools::includeMarkdown("hom_l1_text.md")

```


# Heatmap Valores Relativos

## Row 


### Column {width=80%}

::: {.card title="Mapa de Calor con Tasa de Homicidios"}

```{r}
#| label: mapa de calor homicidios con tasa
#| fig.width: 16
#| fig.height: 6

# importa datos
dt_homic_tasa <- 
  read_rds("raw_data/homic_tasa.rds")

# plot mapa de calor
dt_homic_tasa  |> 
  filter(año > 2015) |> 
  na.omit() |>  
  mutate(estado = factor(estado, 
                         levels = rev(sort(unique(estado)))),
         texto = paste0(estado, "\n",
                        año, mes, "\n",
                        tasa_mes)) |> 
  ggplot(aes(x = fecha,
             y = estado, 
             fill = tasa_mes)) +
    geom_tile(color = "grey70", 
              alpha = 0.85) +
    scale_fill_gradient(low = "#FFFFFF", 
                        high = "#7B0303",
                        expand = c(0,0)) +
    geom_vline(aes(xintercept = as_date("2018-12-01"), 
                   alpha = 0.15), 
               linewidth = 3, 
               color = "darkgrey") +
    theme_breton() +
    theme(plot.background = element_blank(),
          panel.background = element_rect(fill = "#FFFFFF"),
          legend.position = "top") +
    labs(title = "¿En qué Estados Ocurren Más Homicidios?",
         subtitle = "Proporcion de víctimas de homicidio doloso por cada 100,000 habitantes por Entidad Federativa, de enero de 2016 a abril de 2024.",
         x = NULL,
         y = NULL,
         caption = "Fuente: Reportes de Incidencia Delictiva; 
         Secretariado Ejecutivo del Sistema Nacional de Seguridad Pública, 
         Gobierno de México.<br>
         Visualización: Juan L. Bretón, PMP | @juanlbreton",
         fill = "Víctimas por cada 100,000 habitantes") +
    guides(alpha = guide_legend("Inicio de Sexenio", 
                                label = FALSE,
                                title.vjust =  -0.01)) +
    scale_y_discrete(expand = c(0, 0)) +
    scale_x_date(expand = c(0, 0))
  
```

:::


### Column {width=20%}

```{r}
#| label: texto explicativo l2

htmltools::includeMarkdown("hom_l2_text.md")

```


# Mapa

## Row


### Column {width=70%}

::: {.card title="Mapa de Tasa de Homicidios"}


```{r}
#| label: mapa de tasa de homicidios

mapa_nal_tasa_2023 <- 
  read_rds("raw_data/mapa_nal_tasa_2023.rds")

# limites
vlim <- 
  c(min(mapa_nal_tasa_2023$tasa),
    max(mapa_nal_tasa_2023$tasa))

# plot de mapa
mapa_nal_tasa_2023 |> 
  ggplot(aes(fill = tasa)) +
  geom_sf(color = "grey60",
          size = 0.7) +
  theme_breton() +
  theme(plot.background = element_blank(),
        panel.background = element_rect(fill = "#FFFFFF"),
        panel.grid = element_blank(),
        panel.border = element_blank(),
        panel.grid.major = element_blank(),
        axis.line = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank()) +
  labs(title = "Geografía de la Violencia Homicida",
       subtitle = "Víctimas de homicidio doloso por cada 100,000 habitantes en el año 2023",
       caption = "Fuente: Reportes de Incidencia Delictiva; 
       Secretariado Ejecutivo del Sistema Nacional de Seguridad Pública, 
             Gobierno de México. 
             <br>CONAPO Conciliaciones de población.<br>
             Visualización: Juan L. Bretón, PMP | @BretonPmp") +
  scale_fill_gradient(name = "Tasa de\nvíctimas por\n100,000 habs", 
                      low = "#FFFFFF",
                      high = "#7B0303",
                      limits = vlim,
                      breaks = round(seq(vlim[1],
                                         vlim[2],
                                         length.out = 5),
                                     digits = 1))
```


:::

### Column {width=30%}

```{r}
#| label: texto explicativo l3

htmltools::includeMarkdown("hom_l3_text.md")
```


# Tendencias

## Row

### Column {width=80%}

::: {.card title="Tendencias de Homicidios"}

```{r}
#| label: tendencias homicidios

# data
dt_homic_sim <- 
  dt_homic |>
  select(rowid, id_entidad, año, num_mes, 
         mes, fecha, estado, homicidios)

# Plot de tendencias de homicidios por mes por entidad federativa
dt_homic_sim |>  
  filter(fecha >= as_date("2016-01-01")) |> 
  filter(!fecha > as_date("2024-03-01")) |> 
  ggplot(aes(x = fecha, 
             y = homicidios,
             group = estado)) +
  geom_line(alpha = 0.25) +
  # poisson trend line
  geom_smooth(method = "glm",
              method.args = c("poisson"),
              se = FALSE, 
              linewidth = 0.25,
              color = "darkred") +
  facet_wrap(vars(estado), scales = "free_y") +
  theme_breton() +
  theme(strip.text.x.top = element_text(size = 5.0),
        axis.text = element_text(size = 6)) +
  labs(title = "Tendencias de Homicidios Dolosos",
         subtitle = "Cifras mensuales por estado. La línea roja representa la tendencia simple.",
         x = "Mes",
         y = "Víctimas de homicidio doloso por mes",
         caption = "Fuente: Reportes de Incidencia Delictiva; Secretariado Ejecutivo del Sistema Nacional de Seguridad Pública, 
           Gobierno de México.<br>
           Visualización: Juan L. Bretón, PMP | @juanlbreton")
```


:::



### Column {width=20%}

```{r}
#| label: texto explicativo l4

htmltools::includeMarkdown("hom_l4_text.md")
```


